// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD20309.Models;

#nullable disable

namespace SD20309.Migrations
{
    [DbContext(typeof(SD20309DbContext))]
    [Migration("20250730125856_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD20309.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("MaKhachHang")
                        .HasColumnType("bigint");

                    b.Property<long>("MaNhanVien")
                        .HasColumnType("bigint");

                    b.Property<string>("MaVoucher")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongHoaDon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaVoucher");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("SD20309.Models.HoaDonChiTiet", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.HasKey("MaHoaDon", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("SD20309.Models.KhachHang", b =>
                {
                    b.Property<long>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("SD20309.Models.LoaiSanPham", b =>
                {
                    b.Property<long>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("SD20309.Models.NhanVien", b =>
                {
                    b.Property<long>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("SD20309.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("LoaiSanPhamMaLoai")
                        .HasColumnType("bigint");

                    b.Property<long>("MaLoaiSanPham")
                        .HasColumnType("bigint");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("LoaiSanPhamMaLoai");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.HasKey("Ma");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet_ThuocTinh", b =>
                {
                    b.Property<string>("MaSanPhamChiTiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("MaThuocTinh")
                        .HasColumnType("bigint");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KieuDuLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanPhamChiTiet_ThuocTinhMaSanPhamChiTiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("SanPhamChiTiet_ThuocTinhMaThuocTinh")
                        .HasColumnType("bigint");

                    b.HasKey("MaSanPhamChiTiet", "MaThuocTinh");

                    b.HasIndex("MaThuocTinh");

                    b.HasIndex("SanPhamChiTiet_ThuocTinhMaSanPhamChiTiet", "SanPhamChiTiet_ThuocTinhMaThuocTinh");

                    b.ToTable("SanPhamChiTiet_ThuocTinh");
                });

            modelBuilder.Entity("SD20309.Models.ThuocTinh", b =>
                {
                    b.Property<long>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Ma"));

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma");

                    b.ToTable("ThuocTinh");
                });

            modelBuilder.Entity("SD20309.Models.Voucher", b =>
                {
                    b.Property<string>("MaVoucher")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("GiaTriApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<int>("LoaiGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenVouCher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaVoucher");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("SD20309.Models.HoaDon", b =>
                {
                    b.HasOne("SD20309.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang");

                    b.HasOne("SD20309.Models.NhanVien", "NguoiTaoHoaDon")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("MaVoucher");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiTaoHoaDon");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("SD20309.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("SD20309.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SD20309.Models.SanPham", b =>
                {
                    b.HasOne("SD20309.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("LoaiSanPhamMaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("SD20309.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet_ThuocTinh", b =>
                {
                    b.HasOne("SD20309.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTiet_ThuocTinhs")
                        .HasForeignKey("MaSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.ThuocTinh", "ThuocTinh")
                        .WithMany()
                        .HasForeignKey("MaThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.SanPhamChiTiet_ThuocTinh", null)
                        .WithMany("SanPhamChiTiet_ThuocTinhs")
                        .HasForeignKey("SanPhamChiTiet_ThuocTinhMaSanPhamChiTiet", "SanPhamChiTiet_ThuocTinhMaThuocTinh");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("SD20309.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("SD20309.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("SD20309.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("SanPhamChiTiet_ThuocTinhs");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet_ThuocTinh", b =>
                {
                    b.Navigation("SanPhamChiTiet_ThuocTinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
