// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD20309.Models;

#nullable disable

namespace SD20309.Migrations
{
    [DbContext(typeof(SD20309DbContext))]
    [Migration("20250801114853_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD20309.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("MaKhachHang")
                        .HasColumnType("bigint");

                    b.Property<long>("MaNhanVien")
                        .HasColumnType("bigint");

                    b.Property<string>("MaVoucher")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongHoaDon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaVoucher");

                    b.ToTable("HoaDon");

                    b.HasData(
                        new
                        {
                            MaHoaDon = "HD001",
                            MaKhachHang = 1L,
                            MaNhanVien = 1L,
                            ThanhTien = 25000000.00m,
                            ThoiGianTao = new DateTime(2025, 8, 1, 18, 48, 53, 94, DateTimeKind.Local).AddTicks(7246),
                            TongHoaDon = 25000000.00m,
                            TongTienGiam = 0m
                        },
                        new
                        {
                            MaHoaDon = "HD002",
                            MaKhachHang = 2L,
                            MaNhanVien = 2L,
                            MaVoucher = "SUMMER25",
                            ThanhTien = 34000000.00m,
                            ThoiGianTao = new DateTime(2025, 8, 1, 18, 48, 53, 95, DateTimeKind.Local).AddTicks(54),
                            TongHoaDon = 35000000.00m,
                            TongTienGiam = 1000000.00m
                        });
                });

            modelBuilder.Entity("SD20309.Models.HoaDonChiTiet", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.HasKey("MaHoaDon", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HoaDonChiTiet");

                    b.HasData(
                        new
                        {
                            MaHoaDon = "HD001",
                            MaSanPham = "LT001",
                            DonGia = 25000000.00m,
                            SoLuong = 1L
                        },
                        new
                        {
                            MaHoaDon = "HD002",
                            MaSanPham = "LT002",
                            DonGia = 35000000.00m,
                            SoLuong = 1L
                        });
                });

            modelBuilder.Entity("SD20309.Models.KhachHang", b =>
                {
                    b.Property<long>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKhachHang = 1L,
                            DiaChi = "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
                            Email = "nguyenvana@example.com",
                            HoTen = "Nguyễn Văn A",
                            SoDienThoai = "0901112233"
                        },
                        new
                        {
                            MaKhachHang = 2L,
                            DiaChi = "456 Lê Lợi, Quận 1, TP. Hồ Chí Minh",
                            Email = "tranb@example.com",
                            HoTen = "Trần Thị B",
                            SoDienThoai = "0987654321"
                        });
                });

            modelBuilder.Entity("SD20309.Models.LoaiSanPham", b =>
                {
                    b.Property<long>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPham");

                    b.HasData(
                        new
                        {
                            MaLoai = 1L,
                            MoTa = "Các loại máy tính xách tay đa dụng và chuyên dụng.",
                            TenLoai = "Laptop"
                        },
                        new
                        {
                            MaLoai = 2L,
                            MoTa = "Máy tính để bàn chuyên chơi game hiệu năng cao.",
                            TenLoai = "PC Gaming"
                        },
                        new
                        {
                            MaLoai = 3L,
                            MoTa = "Các loại màn hình máy tính từ phổ thông đến chuyên nghiệp.",
                            TenLoai = "Màn Hình"
                        },
                        new
                        {
                            MaLoai = 4L,
                            MoTa = "Bàn phím cơ, giả cơ và văn phòng.",
                            TenLoai = "Bàn Phím"
                        },
                        new
                        {
                            MaLoai = 5L,
                            MoTa = "Chuột gaming, văn phòng và không dây.",
                            TenLoai = "Chuột"
                        });
                });

            modelBuilder.Entity("SD20309.Models.NhanVien", b =>
                {
                    b.Property<long>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1L,
                            Email = "thunt@example.com",
                            GioiTinh = false,
                            MatKhau = "123456",
                            SoDienThoai = "0909123456",
                            TaiKhoan = "thu_ql",
                            TenNhanVien = "Nguyễn Thị Thu",
                            VaiTro = 1
                        },
                        new
                        {
                            MaNhanVien = 2L,
                            Email = "anhl@example.com",
                            GioiTinh = true,
                            MatKhau = "123456",
                            SoDienThoai = "0978901234",
                            TaiKhoan = "anh_nv",
                            TenNhanVien = "Lê Đức Anh",
                            VaiTro = 0
                        });
                });

            modelBuilder.Entity("SD20309.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("MaLoaiSanPham")
                        .HasColumnType("bigint");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaLoaiSanPham");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            MaSanPham = "LT001",
                            MaLoaiSanPham = 1L,
                            MoTa = "Laptop gaming mạnh mẽ với CPU Intel Core i7 và GPU RTX 3050.",
                            SoLuong = 50L,
                            TenSanPham = "Laptop Gaming Acer Nitro 5"
                        },
                        new
                        {
                            MaSanPham = "LT002",
                            MaLoaiSanPham = 1L,
                            MoTa = "Laptop cao cấp cho công việc và thiết kế.",
                            SoLuong = 30L,
                            TenSanPham = "Laptop Dell XPS 15"
                        },
                        new
                        {
                            MaSanPham = "MH001",
                            MaLoaiSanPham = 3L,
                            MoTa = "Màn hình 4K IPS chuyên đồ họa.",
                            SoLuong = 40L,
                            TenSanPham = "Màn Hình Dell UltraSharp U2723QE"
                        });
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SoLuong")
                        .HasColumnType("bigint");

                    b.HasKey("Ma");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamChiTiet");

                    b.HasData(
                        new
                        {
                            Ma = "LT001_1",
                            AnhSP = "https://example.com/images/acer-nitro-5-1.jpg",
                            Gia = 25000000.00m,
                            MaSanPham = "LT001",
                            SoLuong = 20L
                        },
                        new
                        {
                            Ma = "LT001_2",
                            AnhSP = "https://example.com/images/acer-nitro-5-2.jpg",
                            Gia = 28500000.00m,
                            MaSanPham = "LT001",
                            SoLuong = 30L
                        },
                        new
                        {
                            Ma = "MH001_B",
                            AnhSP = "https://example.com/images/dell-monitor-b.jpg",
                            Gia = 12000000.00m,
                            MaSanPham = "MH001",
                            SoLuong = 40L
                        });
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet_ThuocTinh", b =>
                {
                    b.Property<string>("MaSanPhamChiTiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("MaThuocTinh")
                        .HasColumnType("bigint");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KieuDuLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanPhamChiTiet_ThuocTinhMaSanPhamChiTiet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("SanPhamChiTiet_ThuocTinhMaThuocTinh")
                        .HasColumnType("bigint");

                    b.HasKey("MaSanPhamChiTiet", "MaThuocTinh");

                    b.HasIndex("MaThuocTinh");

                    b.HasIndex("SanPhamChiTiet_ThuocTinhMaSanPhamChiTiet", "SanPhamChiTiet_ThuocTinhMaThuocTinh");

                    b.ToTable("SanPhamChiTiet_ThuocTinh");

                    b.HasData(
                        new
                        {
                            MaSanPhamChiTiet = "LT001_1",
                            MaThuocTinh = 1L,
                            GiaTri = "Đen"
                        },
                        new
                        {
                            MaSanPhamChiTiet = "LT001_1",
                            MaThuocTinh = 2L,
                            GiaTri = "Intel Core i7-12700H"
                        },
                        new
                        {
                            MaSanPhamChiTiet = "LT001_1",
                            MaThuocTinh = 3L,
                            GiaTri = "16GB DDR4"
                        },
                        new
                        {
                            MaSanPhamChiTiet = "MH001_B",
                            MaThuocTinh = 1L,
                            GiaTri = "Đen"
                        });
                });

            modelBuilder.Entity("SD20309.Models.ThuocTinh", b =>
                {
                    b.Property<long>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Ma"));

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma");

                    b.ToTable("ThuocTinh");

                    b.HasData(
                        new
                        {
                            Ma = 1L,
                            TenThuocTinh = "Màu Sắc"
                        },
                        new
                        {
                            Ma = 2L,
                            TenThuocTinh = "Bộ Vi Xử Lý"
                        },
                        new
                        {
                            Ma = 3L,
                            TenThuocTinh = "RAM"
                        },
                        new
                        {
                            Ma = 4L,
                            TenThuocTinh = "Ổ Cứng"
                        });
                });

            modelBuilder.Entity("SD20309.Models.Voucher", b =>
                {
                    b.Property<string>("MaVoucher")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("GiaTriApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<int>("LoaiGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenVouCher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaVoucher");

                    b.ToTable("Voucher");

                    b.HasData(
                        new
                        {
                            MaVoucher = "SUMMER25",
                            GiaTriApDung = 5000000.00m,
                            GiaTriGiam = 0.25m,
                            GiaTriGiamToiDa = 1000000.00m,
                            HanSuDung = new DateOnly(2025, 8, 31),
                            LoaiGiam = 0,
                            TenVouCher = "Ưu đãi hè 25%",
                            TrangThai = true
                        },
                        new
                        {
                            MaVoucher = "FREESHIP",
                            GiaTriApDung = 1000000.00m,
                            GiaTriGiam = 30000.00m,
                            GiaTriGiamToiDa = 0.00m,
                            HanSuDung = new DateOnly(2025, 12, 31),
                            LoaiGiam = 1,
                            TenVouCher = "Miễn phí vận chuyển",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("SD20309.Models.HoaDon", b =>
                {
                    b.HasOne("SD20309.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang");

                    b.HasOne("SD20309.Models.NhanVien", "NguoiTaoHoaDon")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("MaVoucher");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiTaoHoaDon");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("SD20309.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("SD20309.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SD20309.Models.SanPham", b =>
                {
                    b.HasOne("SD20309.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("MaLoaiSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("SD20309.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet_ThuocTinh", b =>
                {
                    b.HasOne("SD20309.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamChiTiet_ThuocTinhs")
                        .HasForeignKey("MaSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.ThuocTinh", "ThuocTinh")
                        .WithMany()
                        .HasForeignKey("MaThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD20309.Models.SanPhamChiTiet_ThuocTinh", null)
                        .WithMany("SanPhamChiTiet_ThuocTinhs")
                        .HasForeignKey("SanPhamChiTiet_ThuocTinhMaSanPhamChiTiet", "SanPhamChiTiet_ThuocTinhMaThuocTinh");

                    b.Navigation("SanPhamChiTiet");

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("SD20309.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("SD20309.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("SD20309.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("SanPhamChiTiet_ThuocTinhs");
                });

            modelBuilder.Entity("SD20309.Models.SanPhamChiTiet_ThuocTinh", b =>
                {
                    b.Navigation("SanPhamChiTiet_ThuocTinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
